// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvcygfPPVG3iiP2oXBpByw5UJnI_70AQ',
    appId: '1:313966874532:web:ee74a9a0d08062eae5bb31',
    messagingSenderId: '313966874532',
    projectId: 'base-e7ab7',
    authDomain: 'base-e7ab7.firebaseapp.com',
    storageBucket: 'base-e7ab7.appspot.com',
    measurementId: 'G-1QC78CBFH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYmWHx9_x4N80PL1jVAHsc-mxnv_4iOo',
    appId: '1:313966874532:android:349d8240a2545954e5bb31',
    messagingSenderId: '313966874532',
    projectId: 'base-e7ab7',
    storageBucket: 'base-e7ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aQLNIMnXaMxva26iPy6M7IHm25yr6X4',
    appId: '1:313966874532:ios:f07da14bfdc5e0cee5bb31',
    messagingSenderId: '313966874532',
    projectId: 'base-e7ab7',
    storageBucket: 'base-e7ab7.appspot.com',
    iosClientId: '313966874532-95s5bfalmgvu84tvqsa2u413fkc4s0rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.base',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6aQLNIMnXaMxva26iPy6M7IHm25yr6X4',
    appId: '1:313966874532:ios:f07da14bfdc5e0cee5bb31',
    messagingSenderId: '313966874532',
    projectId: 'base-e7ab7',
    storageBucket: 'base-e7ab7.appspot.com',
    iosClientId: '313966874532-95s5bfalmgvu84tvqsa2u413fkc4s0rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.base',
  );
}
